import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Script from "next/script";
import style from "./globals.module.css";
import {cookies} from "next/headers";
import  axios  from "axios";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme")?.value || "#F8F9FA";
  const jwt = cookieStore.get("jwt")?.value || "";
  axios.defaults.headers.common["Authorization"] = `Bearer ${jwt}`; //axiosのデフォルトヘッダーにjwtを設定 
  return (
    <html lang="ja">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossOrigin="anonymous"
        />
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
          crossOrigin="anonymous"
        ></Script>
      </head>
      {theme == "#F8F9FA" ? (
          <body className={style.body} >{children}</body>
      ):(
          <body className={style.bodyDark}>{children}</body>
      )}
    </html>
  );
}
